name = "MSBuild"
grammar = "xml"
path_suffixes = [
  "csproj",
  "fsproj",
  "vbproj",
  "vcxproj",
  "sqlproj",
  "wixproj",
  "shproj",
  "njsproj",
  "pyproj",
  "props",
  "targets",
  "tasks",
  "pubxml",
]
block_comment = ["<!-- ", " -->"]
brackets = [{ start = "<", end = ">", close = true, newline = true }]
